### ISSUE TITLE
app crashing when I load a CSV file

### ISSUE THREAD

**Issue by pixy61** [smouksassi/ggplotwithyourdata#20] opened 2020-01-31 14:37 UTC
Shiny app crashed even when I try to load example data. I keep getting the same errors:
Listening on http://127.0.0.1:4227
Warning: Error in : 1 components of `...` had unexpected names.

We detected these problematic arguments:
* `gather_cols`
Did you misspecify an argument?
  128: <Anonymous>
Warning: Error in : 1 components of `...` had unexpected names.
We detected these problematic arguments:
* `gather_cols`
............
Am I doing something wrong?

**Comment by smouksassi** [comment] 2020-01-31 15:16
thanks for reporting it might be due to a newer version of tidyr ? can you provide a session info ?
will be helpful  to include a sample data that can reproduce your error do you have special characters in your variable names ?

**Comment by pixy61** [comment] 2020-02-04 09:22
I have the same problem! App keep crashing even with sample data set!

**Comment by smouksassi** [comment] 2020-02-04 11:54
can you provide a session info it works fine on my end and I need a way to see what is happening or provide some error output that you see in the console.

**Comment by pixy61** [comment] 2020-02-04 12:20
actually I put the file with the info as attachment to my previous message but evidently it didn't work. I'm trying again. Let me know

**Comment by smouksassi** [comment] 2020-02-04 12:23
indeed it did not attach any file ideally provide a minimal data that I can run on my end using the dev version and see what is going on.
Which version are you using ? also provide the output of your 
```r
sessionInfo()
```

**Comment by pixy61** [comment] 2020-02-04 12:23
Not sure it worked so I'm rewriting the log session here: 
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 10 x64 (build 10586)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] table1_1.1         ggquickeda_0.1.5   ggpmisc_0.3.3      plotly_4.9.1       ggrepel_0.8.1      lazyeval_0.2.2    
 [7] rlang_0.4.4        markdown_1.1       quantreg_5.54      SparseM_1.78       Hmisc_4.3-0        Formula_1.2-3     
[13] survival_3.1-8     lattice_0.20-38    dplyr_0.8.4        tidyr_1.0.2        DT_0.11            scales_1.1.0      
[19] ggplot2_3.3.0.9000 colourpicker_1.0   shinyjs_1.1        shiny_1.4.0        RISmed_2.1.7      

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3            knitr_1.27            magrittr_1.5          cluster_2.1.0         splines_3.6.2        
 [6] tidyselect_1.0.0.9000 viridisLite_0.3.0     xtable_1.8-4          colorspace_1.4-1      R6_2.4.1             
[11] jpeg_0.1-8.1          xfun_0.12             latticeExtra_0.6-29   withr_2.1.2           ellipsis_0.3.0       
[16] MatrixModels_0.4-1    htmltools_0.4.0       assertthat_0.2.1      digest_0.6.23         tibble_2.1.3         
[21] lifecycle_0.1.0       Matrix_1.2-18         acepack_1.4.1         compiler_3.6.2        pillar_1.4.3         
[26] backports_1.1.5       jsonlite_1.6.1        httpuv_1.5.2          pkgconfig_2.0.3       rstudioapi_0.10      
[31] munsell_0.5.0         fastmap_1.0.1         httr_1.4.1            stringr_1.4.0         tools_3.6.2          
[36] grid_3.6.2            nnet_7.3-12           htmlTable_1.13.3      data.table_1.12.8     gtable_0.3.0         
[41] checkmate_1.9.4       png_0.1-7             miniUI_0.1.1.1        crosstalk_1.0.0       yaml_2.2.1           
[46] crayon_1.3.4          gridExtra_2.3         purrr_0.3.3           later_1.0.0           RColorBrewer_1.1-2   
[51] promises_1.1.0        htmlwidgets_1.5.1     base64enc_0.1-3       vctrs_0.2.99.9005     rsconnect_0.8.16     
[56] rpart_4.1-15          glue_1.3.1            mime_0.8              stringi_1.4.5         foreign_0.8-75       
[61] Cairo_1.5-10

**Comment by smouksassi** [comment] 2020-02-04 12:26
I see you are using the dev version of ggplot, tidyselect and vctrs. can you launch the app from Rstudio and try it and see copy paste what you see in the console ?

I need more than:
gather_cols
Did you misspecify an argument?
128:
Warning: Error in : 1 components of ... had unexpected names.

**Comment by smouksassi** [comment] 2020-02-04 12:29
alternatively try the dev version from github and let me know if it still breaks

**Comment by pixy61** [comment] 2020-02-04 13:50
Here it is:
shiny::runApp('shinyapp')
Loading required package: shiny
Need Shiny help? I'm available for consulting:
	http://attalitech.com

Attaching package: ‘shinyjs’

The following object is masked from ‘package:shiny’:

    runExample

The following objects are masked from ‘package:methods’:

    removeClass, show


Attaching package: ‘colourpicker’

The following objects are masked from ‘package:shinyjs’:

    colourInput, colourPicker, runExample, updateColourInput

The following object is masked from ‘package:shiny’:

    runExample


Attaching package: ‘DT’

The following objects are masked from ‘package:shiny’:

    dataTableOutput, renderDataTable


Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Loading required package: lattice
Loading required package: survival
Loading required package: Formula

Attaching package: ‘Hmisc’

The following objects are masked from ‘package:dplyr’:

    src, summarize

The following object is masked from ‘package:shinyjs’:

    html

The following objects are masked from ‘package:base’:

    format.pval, units

Loading required package: SparseM

Attaching package: ‘SparseM’

The following object is masked from ‘package:base’:

    backsolve


Attaching package: ‘quantreg’

The following object is masked from ‘package:Hmisc’:

    latex

The following object is masked from ‘package:survival’:

    untangle.specials


Attaching package: ‘lazyeval’

The following objects are masked from ‘package:rlang’:

    as_name, call_modify, call_standardise, expr_label, expr_text, f_env, f_env<-, f_label, f_lhs, f_lhs<-, f_rhs,
    f_rhs<-, f_text, is_atomic, is_call, is_formula, is_lang, is_pairlist, missing_arg


Attaching package: ‘plotly’

The following object is masked from ‘package:Hmisc’:

    subplot

The following object is masked from ‘package:ggplot2’:

    last_plot

The following object is masked from ‘package:stats’:

    filter

The following object is masked from ‘package:graphics’:

    layout


Attaching package: ‘ggquickeda’

The following object is masked from ‘package:base’:

    +


Attaching package: ‘table1’

The following object is masked _by_ ‘.GlobalEnv’:

    eqcut

The following objects are masked from ‘package:Hmisc’:

    label, label<-, units

The following objects are masked from ‘package:base’:

    units, units<-


Listening on http://127.0.0.1:5192
Warning: Error in : 1 components of `...` had unexpected names.

We detected these problematic arguments:
* `gather_cols`

Did you misspecify an argument?
  128: <Anonymous>
Warning: Error in : 1 components of `...` had unexpected names.

We detected these problematic arguments:
* `gather_cols`

Did you misspecify an argument?
  99: <Anonymous>
Warning: Error in : 1 components of `...` had unexpected names.

We detected these problematic arguments:
* `gather_cols`

Did you misspecify an argument?
  116: <Anonymous>
Warning: Error in : 1 components of `...` had unexpected names.

We detected these problematic arguments:
* `gather_cols`

Did you misspecify an argument?
  99: <Anonymous>
Warning: Error in : 1 components of `...` had unexpected names.

We detected these problematic arguments:
* `gather_cols`

Did you misspecify an argument?
  64: <Anonymous>
Warning: Error in : 1 components of `...` had unexpected names.

We detected these problematic arguments:
* `gather_cols`

Did you misspecify an argument?
  133: <Anonymous>
Warning: Error in : 1 components of `...` had unexpected names.

We detected these problematic arguments:
* `gather_cols`

Did you misspecify an argument?
  99: <Anonymous>
Warning: Error in : 1 components of `...` had unexpected names.

We detected these problematic arguments:
* `gather_cols`

Did you misspecify an argument?
  99: <Anonymous>
Warning: Error in : 1 components of `...` had unexpected names.

We detected these problematic arguments:
* `gather_cols`

Did you misspecify an argument?
  99: <Anonymous>
Warning: Error in : 1 components of `...` had unexpected names.

We detected these problematic arguments:
* `gather_cols`

Did you misspecify an argument?
  99: <Anonymous>
Warning: Error in : 1 components of `...` had unexpected names.

We detected these problematic arguments:
* `gather_cols`

Did you misspecify an argument?
  99: <Anonymous>
Warning: Error in : 1 components of `...` had unexpected names.

We detected these problematic arguments:
* `gather_cols`

Did you misspecify an argument?
  99: <Anonymous>
Warning: Error in : 1 components of `...` had unexpected names.

We detected these problematic arguments:
* `gather_cols`

Did you misspecify an argument?
  99: <Anonymous>
Warning: Error in : 1 components of `...` had unexpected names.

We detected these problematic arguments:
* `gather_cols`

Did you misspecify an argument?
  99: <Anonymous>
Warning: Error in : 1 components of `...` had unexpected names.

We detected these problematic arguments:
* `gather_cols`

Did you misspecify an argument?
  99: <Anonymous>
Warning: Error in : 1 components of `...` had unexpected names.

We detected these problematic arguments:
* `gather_cols`

Did you misspecify an argument?
  187: <Anonymous>
Warning: Error in : 1 components of `...` had unexpected names.

We detected these problematic arguments:
* `gather_cols`

Did you misspecify an argument?
  61: <Anonymous>

**Comment by smouksassi** [comment] 2020-02-04 13:58
there is no use of `gather_cols` in the cran version of the app 
```r
gather ( , gather_cols = ) 
```
what happens if you run the app directly from github ?

**Comment by smouksassi** [comment] 2020-02-04 14:01
ok now I know what is going on please use the package: ggquickeda this package is outdated and should not be used

**Comment by smouksassi** [comment] 2020-02-04 14:10
reinstall from github and try again. but the ggquickeda has more features and the only one being supported moving forward.

**Comment by pixy61** [comment] 2020-02-04 14:47
it worked if launched directly from github with the command: shiny :: runGitHub ('ggplotwithyourdata', 'smouksassi', subdir = 'shinyapp')
I uninstalled ggquickeda and reinstalled with the command: devtools :: install_github ("smouksassi / ggquickeda")
But I get the same error and it’s not working. Note that if I run ggquickeda directly with the command: run_ggquickeda () everything works perfectly

**Comment by smouksassi** [comment] 2020-02-04 17:38
Please close this issue and open another one in the right package repo if you still have issues. ( I updated the problematic code in ggplotwithyourdata)

**Closed as completed** 2020-02-05 11:07 UTC
